// Code generated by SQLBoiler 4.14.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	ReferralcodeRejectionReason string
	TBLConfig                   string
	TBLReferralcodes            string
	TBLUsers                    string
}{
	ReferralcodeRejectionReason: "referralcode_rejection_reason",
	TBLConfig:                   "tbl_config",
	TBLReferralcodes:            "tbl_referralcodes",
	TBLUsers:                    "tbl_users",
}
